platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!
target 'SLAPP' do
    pod 'UMCCommon'
    pod 'UMCSecurityPlugins'
    pod 'UMCAnalytics'
    pod 'AFNetworking', '~> 3.2.1'
    pod 'SDWebImage','~> 4.4.3'
    pod 'HandyJSON'
    pod 'MJExtension', '~> 3.0.15.1'
    pod 'Masonry'
    pod 'Realm','3.7.4'
    pod 'ChameleonFramework'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'Result','3.2.4'
    pod 'pop'
    pod 'Toast'
    pod 'SVProgressHUD'
    pod 'ReactiveCocoa','7.2.0'
    pod 'ReactiveObjC','3.1.0'
    pod 'JTCalendar'
    pod 'IQKeyboardManager'
    pod 'MJRefresh'
    pod 'Charts','3.1.1'
    pod 'UMengUShare'
    pod 'ZHRefresh'
    pod 'WZLBadge'
    pod 'SnapKit'
    pod 'LameTool'
    pod 'R.swift','~> 4.0.0'
    pod 'R.swift.Library',' ~> 4.0.0'
    pod 'Kingfisher','~> 4.8.1'
    pod 'RongCloudIM/IMLib'
    pod 'RongCloudIM/IMKit'
    pod 'RongCloudIM/CallLib'
    pod 'RongCloudIM/CallKit'
    pod 'LJContactManager'
    pod 'SwiftyJSON'
    pod 'SCSiriWaveformView'
    pod 'KMPlaceholderTextView', '~> 1.3.0'
    pod 'LFProgressView', '~> 1.3.4'
    pod 'ASProgressPopUpView', '~> 0.9'
    pod 'YBPopupMenu', '~> 1.1.2'
    pod 'LYEmptyView', '~> 1.1.0'
    pod 'Siren','3.4.3'
    pod 'iOS-Echarts','1.4.4'
    pod 'NullSafe', '~> 1.2.3'
    pod 'UITextView+Placeholder'
    pod 'YYText'
    pod 'QBImagePickerController'
    
end
